### ISSUE TITLE
无法查看下学期的日程

### ISSUE THREAD

**Issue by yeeus** [Celechron/Celechron#1]
![Screenshot_2024-01-23-12-43-42-770_xyz nosig celechron](https://github.com/Celechron/Celechron/assets/118142448/4cd929dd-a4dd-48c8-a33e-1d07ac74f8b4)
下学期的课程现在无法显示
请问这个是bug还是只有到开学才显示

**Comment by iotang** [comment]
学校还没有发布校历，所以没有显示
等学校发布校历就可以了

**Comment by n0sig** [comment]
已更新，刷新即可查看
（我下个学期没课了，看不了orz）
