### ISSUE TITLE
日程小组件无法显示

### ISSUE THREAD

**Issue by wood6s** [Celechron/Celechron#21]
iPhone15pro更新iOS18.0系统后显示日程（上课时间）的小组件无法正常显示，经过交流发现此问题并非个例，重启手机等操作均无法解决。

**Comment by n0sig** [comment]
理论上已经修复

**Comment by wood6s** [comment]
经测试，还是没有修复，但是非常感谢开发者的关心，希望能够及时修复

**Comment by n0sig** [comment]
我这边尝试了三台不同的手机，都没有遇到这个问题（甚至老版本也没有问题）。您可以卸载了重新安装一次试试。

On Sep 23, 2024, at 00:10, wood6s ***@***.***> wrote:

﻿

经测试，还是没有修复，但是非常感谢开发者的关心，希望能够及时修复

**Comment by wood6s** [comment]
![IMG_6736](https://github.com/user-attachments/assets/cfa28276-0213-4dbe-9a9f-5189ca337b8a)
您好，我跟另一个同学（手机型号同为15pro，系统版本号均为18.0）都尝试了重装与重启，但仍然无法正常显示，如上图所示。我不是专业的iOS开发者，但是我认为这个问题可能跟特定的手机型号（15pro）有关。请问此软件有方法导出日志吗，或许我可以将日志发送给您，方便您进一步解决问题。或者可以等iOS18更新几个版本之后再看此问题是否仍然存在，谢谢。

**Comment by n0sig** [comment]
我就是15pro，升级之后没有遇到问题。
iOS小组件显示这个界面一般是因为小组件的TimelineProvider函数跑崩了，但如果是升级之后才出现问题，那说明应该不是程序的逻辑问题。具体可能要上真机调试才能搞定，说不定是因为一些离谱的课程导致的。

**Comment by wood6s** [comment]
![IMG_6737](https://github.com/user-attachments/assets/ab8ee293-5c26-48d3-bc55-2705bb3f4930)
用另一个同学的通行证登陆后确实可以正常显示，应该就是有些课程不兼容，以及这是我的课表

**Comment by n0sig** [comment]
好消息，我也遇到bug了
