### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by GeorgeC6** [Celechron/Celechron#8]
不论是否使用校网登陆，都会弹出“无法登录研究生院网，Invalid login info”的错误提示
0.2.4 beta版，iOS

**Comment by cxz66666** [comment]
目前无法复现问题，推测是特定时刻研究生院网问题，请确保使用的是zju统一认证账号，如果还有问题请反馈

**Comment by GeorgeC6** [comment]
我用的是统一认证账号，若账号密码错误很快会有另外的提示。
刚刚用0.2.3的release版本又编译了一份，测试发现登录很顺利。

**Comment by cxz66666** [comment]
方便的话能透露下学号前三位吗

**Comment by GeorgeC6** [comment]
323，大一

**Comment by cxz66666** [comment]
这是因为0.2.3中没有进行本科生/研究生的判断，给任何用户都尝试登录了研究生院网和本科生院网，该问题已经在0.2.4中修复，请到testflight中下载0.2.4(2)最新版，或使用新release的0.2.4尝试编译

**Comment by cxz66666** [comment]
或许你可以试试登录 http://yjsy.zju.edu.cn/ 看看能否登录

**Comment by GeorgeC6** [comment]
试过，我是没有权限进去的。

**Comment by GeorgeC6** [comment]
TestFlight的0.2.4(1)版本我也遇到了同样的问题

**Comment by n0sig** [comment]
> 我用的是统一认证账号，若账号密码错误很快会有另外的提示。 刚刚用0.2.3的release版本又编译了一份，测试发现登录很顺利。

奇怪，0.2.3和0.2.4的本科生爬虫是完全一致的

**Comment by n0sig** [comment]
wsdd，0.2.3忘记报错了（

**Comment by GeorgeC6** [comment]
> wsdd，0.2.3忘记报错了（

难绷

**Comment by GeorgeC6** [comment]
> 试过，我是没有权限进去的。

要不设置一个本科生/研究生的切换界面？不然本科生无法访问研究生院网就卡在报错了🙏🏻

**Comment by n0sig** [comment]
已修复

**Comment by n0sig** [comment]
已分发

**Comment by GeorgeC6** [comment]
> 已修复，马上分发（要不你先编译试试

自己编译的和TestFlight上的都已解决了问题👍🏻
